# Site settings
title: DVBR - Brandschutz und Rettung
description: "Beratung und Prüfung von Brandschutz und Arbeitssicherheit in Unternehmen"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: DV für Brandschutz und Rettung
    hero_description: Brandschutz und Rettung

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone:  089 954537619 
    email: info@dvbr.org
    address: DVBR, Hagweg 112,  82024 Taufkirchen, DE

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: DVBR, Hagweg 112,  82024 Taufkirchen, DE
    address_details: img/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2017 DVBR - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
